### ISSUE TITLE
Update model to apply Upper Above Dam survival benefits

### ISSUE THREAD

**Issue by ErinCain** [Reorienting-to-Recovery/springRunDSM#2]
The TMH update added habitat but did not create different segments. We need to apply logic that benefits above dam fish. 

Generate above dam hab percentages 
- [x] Calculate the percentage of spawning habitat that is above the dam in each tributary, and create a data object `above_dam_spawn_hab_prop = c(prop for each 31 watersheds, if no above dam habitat 0)`
- [x] Calculate the percentage of rearing habitat that is above the dam in each tributary, and create a data object - fry and juv `above_dam_rearing_hab_prop = c(prop for each 31 watersheds, if no above dam habitat 0)` 

And above dam temp proxy - do we have median elevation 
- [x] Assume above dam temps are always below threshold that would affect survival 

Update model logic to treat the above dam percentage of fish differently than the below dam (lets pair on this piece. let me know when you are done with above logic and we can do this together) 

Adult logic 
- [x] Create 2 survival probs for prespawn survival, above dam fish do not get adverse temp effects 

Think through this logic but wait to implement until talking through with Rene 
Juvenile Logic - not sure exactly what this will look like but hoping we can do it without changing the routing effects too much. I think we can apply two types of routing survival, one for above dam and one for below, and apply based on habitat proportion above vs below dam) 
- [ ] Create 2 survival probs for rearing, above dam fish do not get adverse temp effects 
- [ ] Split juveniles into above dam and below dam within each rearing function, apply different survivals.

**Comment by MaddeeRubenson** [comment]
Implementation notes are here: https://docs.google.com/document/d/1FcA0Yaw0nCyiPLikR-F1RU8SZaIUiIo4po6wO-IFfrs/edit?usp=sharing

**Comment by ErinCain** [comment]
I updated in the wip spring run branch
